import { useState, useEffect } from 'react';
import { AlertTriangle, X } from 'lucide-react';
import { API_BASE } from '../config';

function formatTime(ts) {
  return new Date(ts).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}

export default function Alerts() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('');
  const [selectedAlert, setSelectedAlert] = useState(null);

  useEffect(() => {
    const params = filter ? `?severity=${filter}` : '';
    fetch(`${API_BASE}/api/alerts${params}`)
      .then(r => r.json())
      .then(d => { setData(d); setLoading(false); })
      .catch(() => setLoading(false));
  }, [filter]);

  if (loading) return <div className="loading-state"><div className="loading-spinner" /><span>Loading alerts...</span></div>;
  if (!data) return <div className="empty-state">Failed to load alerts.</div>;

  const { alerts, summary } = data;

  return (
    <div className="animate-in">
      <div className="page-header">
        <h2>Anomaly Alerts</h2>
        <p>Security alerts generated by the behavioral analysis engine</p>
      </div>

      {/* Summary Cards */}
      <div className="kpi-grid" style={{ marginBottom: 20 }}>
        {[
          { label: 'Total Alerts', value: summary.total, color: '#6366f1', bg: 'rgba(99,102,241,0.12)' },
          { label: 'Critical', value: summary.critical, color: '#ef4444', bg: 'rgba(239,68,68,0.12)' },
          { label: 'High', value: summary.high, color: '#f97316', bg: 'rgba(249,115,22,0.12)' },
          { label: 'Medium', value: summary.medium, color: '#eab308', bg: 'rgba(234,179,8,0.12)' },
          { label: 'Low', value: summary.low, color: '#22d3ee', bg: 'rgba(34,211,238,0.12)' },
        ].map((item, i) => (
          <div key={i} className="kpi-card" style={{ '--kpi-color': item.color, '--kpi-bg': item.bg }}>
            <div className="kpi-icon"><AlertTriangle size={20} /></div>
            <div className="kpi-info">
              <div className="kpi-label">{item.label}</div>
              <div className="kpi-value">{item.value}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Filter Chips */}
      <div className="filter-bar">
        <div className="filter-chips">
          {['', 'critical', 'high', 'medium', 'low'].map(sev => (
            <button key={sev} className={`filter-chip ${filter === sev ? 'active' : ''}`}
              onClick={() => setFilter(sev)}>
              {sev || 'All'}
            </button>
          ))}
        </div>
      </div>

      {/* Alert List */}
      <div className="glass-card">
        <div className="card-header">
          <h3>Alert Feed ({alerts.length})</h3>
        </div>
        <div style={{ maxHeight: 600, overflowY: 'auto' }}>
          {alerts.map(alert => (
            <div key={alert.id} className="alert-item" onClick={() => setSelectedAlert(alert)}>
              <div className="alert-top">
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <span style={{ color: 'var(--text-accent)', fontSize: 12, fontWeight: 600 }}>{alert.id}</span>
                  <span className="alert-type">{alert.typeLabel}</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <span className={`badge badge-${alert.severity}`}>{alert.severity}</span>
                  <span className="alert-time">{formatTime(alert.timestamp)}</span>
                </div>
              </div>
              <div className="alert-description">{alert.description}</div>
              <div className="alert-meta">
                <div className="user-profile-card">
                  <div className="user-avatar-sm" style={{ width: 28, height: 28, fontSize: 10 }}>
                    {alert.userName.split(' ').map(n => n[0]).join('')}
                  </div>
                  <div className="user-meta">
                    <div className="user-name" style={{ fontSize: 12 }}>{alert.userName}</div>
                    <div className="user-dept">{alert.department}</div>
                  </div>
                </div>
                <span className={`badge ${alert.status === 'resolved' ? 'badge-success' : alert.status === 'investigating' ? 'badge-medium' : 'badge-neutral'}`}>
                  {alert.status}
                </span>
                <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>Confidence: {alert.confidenceScore}%</span>
                <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>Assigned: {alert.assignedTo}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Alert Detail Modal */}
      {selectedAlert && (
        <div className="modal-overlay" onClick={() => setSelectedAlert(null)}>
          <div className="modal-content" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Alert Detail — {selectedAlert.id}</h3>
              <button className="modal-close" onClick={() => setSelectedAlert(null)}><X size={16} /></button>
            </div>
            <div className="modal-body">
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 20 }}>
                <div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>Type</div>
                  <div style={{ fontWeight: 600 }}>{selectedAlert.typeLabel}</div>
                </div>
                <div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>Severity</div>
                  <span className={`badge badge-${selectedAlert.severity}`}>{selectedAlert.severity}</span>
                </div>
                <div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>User</div>
                  <div style={{ fontWeight: 600 }}>{selectedAlert.userName}</div>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>{selectedAlert.department}</div>
                </div>
                <div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>Status</div>
                  <span className={`badge ${selectedAlert.status === 'resolved' ? 'badge-success' : 'badge-neutral'}`}>{selectedAlert.status}</span>
                </div>
                <div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>Source IP</div>
                  <div style={{ fontFamily: 'monospace', fontSize: 13 }}>{selectedAlert.sourceIP}</div>
                </div>
                <div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>Confidence Score</div>
                  <div style={{ fontWeight: 700, color: 'var(--accent-primary-light)' }}>{selectedAlert.confidenceScore}%</div>
                </div>
                <div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>Timestamp</div>
                  <div>{formatTime(selectedAlert.timestamp)}</div>
                </div>
                <div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>Assigned To</div>
                  <div>{selectedAlert.assignedTo}</div>
                </div>
              </div>
              <div style={{ padding: 16, background: 'var(--bg-glass)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-primary)' }}>
                <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 6 }}>Description</div>
                <div style={{ fontSize: 13, lineHeight: 1.6 }}>{selectedAlert.description}</div>
              </div>
              <div style={{ marginTop: 20, display: 'flex', gap: 10 }}>
                <button className="btn btn-primary">Mark as Investigating</button>
                <button className="btn btn-ghost">Dismiss</button>
                <button className="btn btn-ghost" style={{ marginLeft: 'auto' }}>Export Details</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
